StepInterval: -1
StepMultiplier: 36000
StepCount: 100
SatelliteDataSource: starlink_1000.tle
SatelliteDataSourceType: tle
GroundStationDataSource: ground_stations.yml
GroundStationDataSourceType: yml
SimulationStartTime: "2025-10-01T00:00:00Z"