package node

import (
	"errors"
	"math"
	"sync"
	"time"

	"github.com/polaris-slo-cloud/stardust-go/pkg/types"
)

var _ types.GroundStation = (*LiveGroundStation)(nil)

// LiveGroundStation represents an Earth-based node that calculates its rotation in real-time.
type LiveGroundStation struct {
	BaseNode

	Latitude                    float64
	Longitude                   float64
	SimulationStartTime         time.Time
	GroundSatelliteLinkProtocol types.GroundSatelliteLinkProtocol

	// This contains the satellites currently visible to this GS, updated by the simulation controller each tick.
	visibleSatellites []types.Satellite
	// this queue holds tasks that have been generated by the workload generator plugin but not yet placed on any satellite.
	taskQueue []types.DeployableService

	mu sync.Mutex
}

// NewLiveGroundStation creates and initializes a real-time ground station.
func NewLiveGroundStation(name string, lat float64, lon float64, protocol types.GroundSatelliteLinkProtocol, simStart time.Time, router types.Router, computing types.Computing) *LiveGroundStation {
	gs := &LiveGroundStation{
		BaseNode: BaseNode{
			Name:      name,
			Router:    router,
			Computing: computing,
		},
		Latitude:                    lat,
		Longitude:                   lon,
		SimulationStartTime:         simStart,
		GroundSatelliteLinkProtocol: protocol,
		taskQueue:                   make([]types.DeployableService, 0),
	}
	protocol.Mount(gs)
	router.Mount(gs)
	computing.Mount(gs)
	gs.updatePositionFromElapsed(0)
	return gs
}

// UpdatePosition sets the current position of the ground station based on simulation time
func (gs *LiveGroundStation) UpdatePosition(simTime time.Time) {
	gs.mu.Lock()
	defer gs.mu.Unlock()

	timeElapsed := simTime.Sub(gs.SimulationStartTime).Seconds()
	gs.updatePositionFromElapsed(timeElapsed)
}

// updatePositionFromElapsed calculates Earth-centered coordinates using geodetic formula
func (gs *LiveGroundStation) updatePositionFromElapsed(timeElapsed float64) {
	const (
		a             = 6378137.0       // semi-major axis in meters
		b             = 6356752.314245  // semi-minor axis in meters
		e2            = 1 - (b*b)/(a*a) // eccentricity squared
		rotationSpeed = 7.2921150e-5    // Earth's rotation speed rad/s
	)

	latRad := types.DegreesToRadians(gs.Latitude)
	lonRad := types.DegreesToRadians(gs.Longitude)
	alt := 0.0

	N := a / math.Sqrt(1-e2*math.Sin(latRad)*math.Sin(latRad))

	x := (N + alt) * math.Cos(latRad) * math.Cos(lonRad)
	y := (N + alt) * math.Cos(latRad) * math.Sin(lonRad)
	z := ((b * b / (a * a) * N) + alt) * math.Sin(latRad)

	theta := rotationSpeed * timeElapsed
	xRot := x*math.Cos(theta) - y*math.Sin(theta)
	yRot := x*math.Sin(theta) + y*math.Cos(theta)
	zRot := z

	gs.Position = types.Vector{X: xRot, Y: yRot, Z: zRot}
}

func (gs *LiveGroundStation) GetLinkNodeProtocol() types.LinkNodeProtocol {
	return gs.GroundSatelliteLinkProtocol
}

// FindNearestSatellite returns the closest satellite in a given list
func (gs *LiveGroundStation) FindNearestSatellite(sats []types.Satellite) (types.Satellite, error) {
	if len(sats) == 0 {
		return nil, errors.New("satellite list is empty")
	}
	nearest := sats[0]
	minDist := gs.DistanceTo(nearest)
	for _, s := range sats[1:] {
		dist := gs.DistanceTo(s)
		if dist < minDist {
			nearest = s
			minDist = dist
		}
	}
	return nearest, nil
}

// SetVisibleSatellites updates the local registry of overseen satellites.
// Wrapped in mutex to prevent race conditions during tick orchestration.
func (gs *LiveGroundStation) SetVisibleSatellites(sats []types.Satellite) {
	gs.mu.Lock()
	defer gs.mu.Unlock()
	gs.visibleSatellites = sats
}

// GetVisibleSatellites returns the overseen satellites.
func (gs *LiveGroundStation) GetVisibleSatellites() []types.Satellite {
	gs.mu.Lock()
	defer gs.mu.Unlock()
	return gs.visibleSatellites
}

// EnqueueTask adds a new task to the local queue in a thread-safe manner.
func (gs *LiveGroundStation) EnqueueTask(task types.DeployableService) {
	gs.mu.Lock()
	defer gs.mu.Unlock()
	gs.taskQueue = append(gs.taskQueue, task)
}

// GetTaskQueue returns a copy of pending tasks to prevent race conditions during orchestration.
func (gs *LiveGroundStation) GetTaskQueue() []types.DeployableService {
	gs.mu.Lock()
	defer gs.mu.Unlock()
	queueCopy := make([]types.DeployableService, len(gs.taskQueue))
	copy(queueCopy, gs.taskQueue)
	return queueCopy
}

// ClearTaskQueue empties the local task queue.
func (gs *LiveGroundStation) ClearTaskQueue() {
	gs.mu.Lock()
	defer gs.mu.Unlock()
	gs.taskQueue = make([]types.DeployableService, 0)
}
